# Generated by Django 2.1.1 on 2018-10-30 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20181023_2146'),
        ('orders', '0002_auto_20181029_2019'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
