# Generated by Django 2.1.1 on 2018-11-01 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billingprofile', '0002_auto_20181030_2119'),
        ('orders', '0003_auto_20181029_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billingprofile.BillingProfile'),
        ),
    ]
